# Generated by Django 2.2.4 on 2019-08-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190809_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='body',
        ),
        migrations.RemoveField(
            model_name='base',
            name='subject',
        ),
    ]
